#define GRIPPER_CLOSED 95
#define GRIPPER_OPENED 50
#define BASE_ROT_CENTER 90
// #define BASE_ROT_MIN 0
// #define BASE_ROT_MAX 180
#define BASE_ROT_MIN 180
#define BASE_ROT_MAX 0
#define SHOULDER_CENTER 82
#define SHOULDER_MIN 0
#define SHOULDER_MAX 180
#define ELBOW_CENTER 91
#define ELBOW_MIN 0
#define ELBOW_MAX 180
#define WRIST_CENTER 98
#define WRIST_MIN 10
#define WRIST_MAX 190
#define WRIST_ROT_CENTER 102
#define WRIST_ROT_MIN 0
#define WRIST_ROT_MAX 190
#define GRIPPER_CENTER 70
#define GRIPPER_MIN 40
#define GRIPPER_MAX 100